/**
 * Category Store
 *
 * Categories are stored on the backend under the user's profile.
 * The store keeps an in-memory cache and syncs with the backend via API calls.
 *
 * On first access, categories are lazily fetched from the server.
 * Mutations (add/remove/update) optimistically update the local cache and fire
 * the corresponding API call. If the API call fails, the change is reverted.
 *
 * Each category now supports: name, type, color (hex), icon (lucide name), is_disabled.
 */

import { create } from "zustand";
import { apiFetch } from "@/lib/api";
import { ENDPOINTS } from "@/lib/constants";
import type { UserCategory } from "@/types";

export type CategoryType = "income" | "expense";

interface CategoryState {
  /** Version counter bumped on every mutation — drives reactive re-renders */
  version: number;
  /** In-memory cache of all user categories */
  items: UserCategory[];
  /** True after the first successful fetch from the backend */
  loaded: boolean;
  /** True while a fetch is in-flight */
  loading: boolean;

  /** Get category names for a given transaction type (excludes disabled) */
  getCategories: (type: CategoryType) => string[];
  /** Get all category objects for a given type (excludes disabled) */
  getCategoryObjects: (type: CategoryType) => UserCategory[];
  /** Get a single category by name (case-insensitive) */
  getCategoryByName: (name: string) => UserCategory | undefined;
  /** Get a single category by stable id */
  getCategoryById: (id: string) => UserCategory | undefined;
  /** Resolve the current display name for a category, by id first then name fallback */
  resolveCategoryName: (categoryName: string, categoryId?: string) => string;
  /** Get the color for a category, by id first then name fallback */
  getCategoryColor: (name: string, categoryId?: string) => string;
  /** Get the icon name for a category, by id first then name fallback */
  getCategoryIcon: (name: string, categoryId?: string) => string | null;
  /** Add a new category under the given transaction type */
  addCategory: (type: CategoryType, category: string) => Promise<void>;
  /** Ensure a category exists and return its id (waits for creation if new) */
  ensureCategory: (type: CategoryType, name: string) => Promise<string | undefined>;
  /** Update a category's fields (name, color, icon, is_disabled) */
  updateCategory: (id: string, updates: Partial<Pick<UserCategory, "name" | "color" | "icon" | "is_disabled">>) => Promise<void>;
  /** Remove a category by id */
  removeCategoryById: (id: string) => Promise<void>;
  /** Remove a category by name + type (legacy) */
  removeCategory: (type: CategoryType, category: string) => Promise<void>;
  /** Fetch categories from the backend (called automatically on first access) */
  fetchCategories: () => Promise<void>;
}

// Deterministic color palette — used when a category has no explicit color set.
// Generated by hashing the category name against this list.
/**
 * Generate a deterministic oklch color for a category name.
 *
 * Uses the hash to pick a hue (0-360), then cycles through four
 * lightness levels (0.60, 0.65, 0.70, 0.75) so that nearby-hue
 * categories get different shades. Chroma is fixed at 0.16 for
 * a balanced pastel saturation.
 *
 * This gives 360 × 4 = 1440 possible distinct colors before any
 * reuse, which is more than enough for any real-world category set.
 */
function hashString(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0; // Convert to 32bit integer
  }
  return Math.abs(hash);
}

function getFallbackColor(categoryName: string): string {
  const hash = hashString(categoryName.toLowerCase().trim());
  const hue = hash % 360;
  const shadeIndex = Math.floor(hash / 360) % 4;
  const lightnesses = [0.60, 0.65, 0.70, 0.75];
  const lightness = lightnesses[shadeIndex];
  return `oklch(${lightness} 0.16 ${hue})`;
}

export const useCategoryStore = create<CategoryState>((set, get) => ({
  version: 0,
  items: [],
  loaded: false,
  loading: false,

  getCategories: (type) => {
    // Trigger lazy load if not loaded yet
    if (!get().loaded && !get().loading) {
      get().fetchCategories();
    }
    return get().items
      .filter((c) => c.type === type)
      .map((c) => c.name)
      .sort((a, b) => a.localeCompare(b));
  },

  getCategoryObjects: (type) => {
    if (!get().loaded && !get().loading) {
      get().fetchCategories();
    }
    return get().items
      .filter((c) => c.type === type)
      .sort((a, b) => a.name.localeCompare(b.name));
  },

  getCategoryByName: (name) => {
    if (!get().loaded && !get().loading) {
      get().fetchCategories();
    }
    return get().items.find(
      (c) => c.name.toLowerCase() === name.toLowerCase()
    );
  },

  getCategoryById: (id) => {
    return get().items.find((c) => c.id === id);
  },

  resolveCategoryName: (categoryName, categoryId) => {
    if (categoryId) {
      const cat = get().items.find((c) => c.id === categoryId);
      if (cat) return cat.name;
    }
    // Fall back to name-based lookup (legacy transactions without category_id)
    const cat = get().items.find(
      (c) => c.name.toLowerCase() === (categoryName || "").toLowerCase()
    );
    if (cat) return cat.name;
    // Category not found (deleted) — show the stored name or "General"
    return categoryName || "General";
  },

  getCategoryColor: (name, categoryId) => {
    if (!get().loaded && !get().loading) {
      get().fetchCategories();
    }
    // First try id-based lookup
    if (categoryId) {
      const catById = get().items.find((c) => c.id === categoryId);
      if (catById?.color) return catById.color;
      if (catById) return getFallbackColor(catById.id);
    }
    // Fall back to name-based lookup (legacy transactions)
    const cat = get().items.find(
      (c) => c.name.toLowerCase() === (name || "").toLowerCase()
    );
    if (cat?.color) return cat.color;
    if (cat) return getFallbackColor(cat.id);
    return getFallbackColor(name || "General");
  },

  getCategoryIcon: (name, categoryId) => {
    if (!get().loaded && !get().loading) {
      get().fetchCategories();
    }
    // First try id-based lookup
    if (categoryId) {
      const catById = get().items.find((c) => c.id === categoryId);
      if (catById?.icon) return catById.icon;
    }
    // Fall back to name-based lookup (legacy transactions)
    const cat = get().items.find(
      (c) => c.name.toLowerCase() === (name || "").toLowerCase()
    );
    return cat?.icon ?? null;
  },

  fetchCategories: async () => {
    set({ loading: true });
    try {
      const data = await apiFetch<UserCategory[]>(ENDPOINTS.categories);
      const items = data ?? [];

      // Assign a persistent color to any category that doesn't have one yet.
      // This ensures the color is saved to the backend and won't change on rename.
      const needsColor = items.filter((c) => !c.color);
      if (needsColor.length > 0) {
        await Promise.all(
          needsColor.map(async (cat) => {
            const color = getFallbackColor(cat.id);
            // Optimistically update in-memory
            const idx = items.findIndex((c) => c.id === cat.id);
            if (idx !== -1) items[idx] = { ...items[idx], color };
            try {
              await apiFetch(ENDPOINTS.updateCategory(cat.id), {
                method: "PUT",
                body: JSON.stringify({ color }),
              });
            } catch { /* non-critical, fallback works for this session */ }
          }),
        );
      }

      set({ items, loaded: true, loading: false });
    } catch {
      set({ loading: false });
    }
  },

  addCategory: async (type, category) => {
    const normalized = category.trim();
    if (!normalized) return;

    // Don't add duplicates
    if (get().items.some((c) => c.type === type && c.name === normalized)) return;

    // Optimistic add with a temp ID (the real ID comes from the server)
    const tempId = `temp_${Date.now()}`;
    const prev = get().items;
    // Use name-based color as a brief placeholder; replaced once the real id is known
    const tempColor = getFallbackColor(normalized);
    set({
      items: [...prev, { id: tempId, user_id: "", name: normalized, type, color: tempColor, created_at: "", is_disabled: false }],
      version: get().version + 1,
    });

    try {
      const created = await apiFetch<UserCategory>(ENDPOINTS.categories, {
        method: "POST",
        body: JSON.stringify({ name: normalized, type }),
      });

      // Compute color from the stable id so it never changes on rename
      const stableColor = getFallbackColor(created.id);

      // Replace the temp entry with the server response, then immediately assign the color
      set({
        items: get().items.map((c) =>
          c.id === tempId
            ? { ...created, color: created.color ?? stableColor, icon: created.icon ?? undefined }
            : c
        ),
      });
      // Persist the color to the backend so future page loads have it
      try {
        await apiFetch(ENDPOINTS.updateCategory(created.id), {
          method: "PUT",
          body: JSON.stringify({ color: stableColor }),
        });
      } catch { /* non-critical — fallback color will be used */ }
    } catch {
      // Revert optimistic add
      set({ items: prev, version: get().version + 1 });
    }
  },

  updateCategory: async (id, updates) => {
    const prev = get().items;
    const target = prev.find((c) => c.id === id);
    if (!target) return;

    // Optimistic update
    set({
      items: prev.map((c) =>
        c.id === id ? { ...c, ...updates } : c
      ),
      version: get().version + 1,
    });

    try {
      const body: Record<string, any> = {};
      if (updates.name !== undefined) body.name = updates.name;
      if (updates.color !== undefined) body.color = updates.color;
      if (updates.icon !== undefined) body.icon = updates.icon;
      if (updates.is_disabled !== undefined) body.is_disabled = updates.is_disabled;

      const updated = await apiFetch<UserCategory>(ENDPOINTS.updateCategory(id), {
        method: "PUT",
        body: JSON.stringify(body),
      });

      // Replace with server response
      set({
        items: get().items.map((c) =>
          c.id === id ? { ...updated, color: updated.color ?? undefined, icon: updated.icon ?? undefined } : c
        ),
      });
    } catch {
      // Revert optimistic update
      set({ items: prev, version: get().version + 1 });
    }
  },

  removeCategoryById: async (id) => {
    const prev = get().items;
    set({
      items: prev.filter((c) => c.id !== id),
      version: get().version + 1,
    });

    try {
      await apiFetch(ENDPOINTS.category(id), { method: "DELETE" });
    } catch {
      // Revert
      set({ items: prev, version: get().version + 1 });
    }
  },

  ensureCategory: async (type, name) => {
    const normalized = name.trim();
    if (!normalized) return undefined;
    // Check if already exists
    const existing = get().items.find((c) => c.type === type && c.name === normalized);
    if (existing) return existing.id;
    // Create it — waits for server response
    await get().addCategory(type, normalized);
    // After creation, find it in the store
    const created = get().items.find((c) => c.type === type && c.name === normalized);
    return created?.id;
  },

  removeCategory: async (type, category) => {
    const target = get().items.find((c) => c.type === type && c.name === category);
    if (!target) return;

    // Optimistic remove
    const prev = get().items;
    set({
      items: prev.filter((c) => c.id !== target.id),
      version: get().version + 1,
    });

    try {
      await apiFetch(ENDPOINTS.category(target.id), { method: "DELETE" });
    } catch {
      // Revert
      set({ items: prev, version: get().version + 1 });
    }
  },
}));
