/**
 * Category Store
 *
 * Categories are stored on the backend under the user's profile.
 * The store keeps an in-memory cache and syncs with the backend via API calls.
 *
 * On first access, categories are lazily fetched from the server.
 * Mutations (add/remove/update) optimistically update the local cache and fire
 * the corresponding API call. If the API call fails, the change is reverted.
 *
 * Each category now supports: name, type, color (hex), icon (lucide name), is_disabled.
 */

import { create } from "zustand";
import { apiFetch } from "@/lib/api";
import { ENDPOINTS } from "@/lib/constants";
import type { UserCategory } from "@/types";

export type CategoryType = "income" | "expense";

interface CategoryState {
  /** Version counter bumped on every mutation — drives reactive re-renders */
  version: number;
  /** In-memory cache of all user categories */
  items: UserCategory[];
  /** True after the first successful fetch from the backend */
  loaded: boolean;
  /** True while a fetch is in-flight */
  loading: boolean;

  /** Get category names for a given transaction type (excludes disabled) */
  getCategories: (type: CategoryType) => string[];
  /** Get all category objects for a given type (excludes disabled) */
  getCategoryObjects: (type: CategoryType) => UserCategory[];
  /** Get a single category by name (case-insensitive, excludes disabled) */
  getCategoryByName: (name: string) => UserCategory | undefined;
  /** Get the color for a category name, or a deterministic default */
  getCategoryColor: (name: string) => string;
  /** Get the icon name for a category, or null */
  getCategoryIcon: (name: string) => string | null;
  /** Add a new category under the given transaction type */
  addCategory: (type: CategoryType, category: string) => Promise<void>;
  /** Update a category's fields (name, color, icon, is_disabled) */
  updateCategory: (id: string, updates: Partial<Pick<UserCategory, "name" | "color" | "icon" | "is_disabled">>) => Promise<void>;
  /** Remove a category by id */
  removeCategoryById: (id: string) => Promise<void>;
  /** Remove a category by name + type (legacy) */
  removeCategory: (type: CategoryType, category: string) => Promise<void>;
  /** Fetch categories from the backend (called automatically on first access) */
  fetchCategories: () => Promise<void>;
}

// Deterministic color palette — used when a category has no explicit color set.
// Generated by hashing the category name against this list.
const FALLBACK_COLORS = [
  "oklch(0.65 0.18 20)",    // red
  "oklch(0.70 0.20 50)",    // orange
  "oklch(0.75 0.18 80)",    // yellow
  "oklch(0.70 0.16 120)",   // green
  "oklch(0.65 0.14 160)",   // teal
  "oklch(0.68 0.16 200)",   // blue
  "oklch(0.65 0.16 240)",   // indigo
  "oklch(0.62 0.18 280)",   // purple
  "oklch(0.65 0.18 320)",   // pink
  "oklch(0.72 0.14 40)",    // ochre
  "oklch(0.70 0.12 100)",   // sage
  "oklch(0.63 0.10 180)",   // ocean
  "oklch(0.68 0.14 10)",    // coral
  "oklch(0.66 0.10 60)",    // gold
  "oklch(0.67 0.15 140)",   // emerald
  "oklch(0.64 0.12 220)",   // sky
];

function hashString(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0; // Convert to 32bit integer
  }
  return Math.abs(hash);
}

function getFallbackColor(categoryName: string): string {
  const hash = hashString(categoryName.toLowerCase().trim());
  return FALLBACK_COLORS[hash % FALLBACK_COLORS.length];
}

export const useCategoryStore = create<CategoryState>((set, get) => ({
  version: 0,
  items: [],
  loaded: false,
  loading: false,

  getCategories: (type) => {
    // Trigger lazy load if not loaded yet
    if (!get().loaded && !get().loading) {
      get().fetchCategories();
    }
    return get().items
      .filter((c) => c.type === type)
      .map((c) => c.name)
      .sort((a, b) => a.localeCompare(b));
  },

  getCategoryObjects: (type) => {
    if (!get().loaded && !get().loading) {
      get().fetchCategories();
    }
    return get().items
      .filter((c) => c.type === type)
      .sort((a, b) => a.name.localeCompare(b.name));
  },

  getCategoryByName: (name) => {
    if (!get().loaded && !get().loading) {
      get().fetchCategories();
    }
    return get().items.find(
      (c) => c.name.toLowerCase() === name.toLowerCase()
    );
  },

  getCategoryColor: (name) => {
    if (!get().loaded && !get().loading) {
      get().fetchCategories();
    }
    const cat = get().items.find(
      (c) => c.name.toLowerCase() === name.toLowerCase()
    );
    if (cat?.color) return cat.color;
    return getFallbackColor(name);
  },

  getCategoryIcon: (name) => {
    if (!get().loaded && !get().loading) {
      get().fetchCategories();
    }
    const cat = get().items.find(
      (c) => c.name.toLowerCase() === name.toLowerCase()
    );
    return cat?.icon ?? null;
  },

  fetchCategories: async () => {
    set({ loading: true });
    try {
      const data = await apiFetch<UserCategory[]>(ENDPOINTS.categories);
      set({ items: data ?? [], loaded: true, loading: false });
    } catch {
      set({ loading: false });
    }
  },

  addCategory: async (type, category) => {
    const normalized = category.trim();
    if (!normalized) return;

    // Don't add duplicates
    if (get().items.some((c) => c.type === type && c.name === normalized)) return;

    // Compute a deterministic default color so the category gets one immediately
    const defaultColor = getFallbackColor(normalized);

    // Optimistic add with a temp ID (the real ID comes from the server)
    const tempId = `temp_${Date.now()}`;
    const prev = get().items;
    set({
      items: [...prev, { id: tempId, user_id: "", name: normalized, type, color: defaultColor, created_at: "", is_disabled: false }],
      version: get().version + 1,
    });

    try {
      const created = await apiFetch<UserCategory>(ENDPOINTS.categories, {
        method: "POST",
        body: JSON.stringify({ name: normalized, type }),
      });
      // Replace the temp entry with the server response, then immediately assign the color
      set({
        items: get().items.map((c) =>
          c.id === tempId
            ? { ...created, color: created.color ?? defaultColor, icon: created.icon ?? undefined }
            : c
        ),
      });
      // Persist the color to the backend so future page loads have it
      try {
        await apiFetch(ENDPOINTS.updateCategory(created.id), {
          method: "PUT",
          body: JSON.stringify({ color: defaultColor }),
        });
      } catch { /* non-critical — fallback color will be used */ }
    } catch {
      // Revert optimistic add
      set({ items: prev, version: get().version + 1 });
    }
  },

  updateCategory: async (id, updates) => {
    const prev = get().items;
    const target = prev.find((c) => c.id === id);
    if (!target) return;

    // Optimistic update
    set({
      items: prev.map((c) =>
        c.id === id ? { ...c, ...updates } : c
      ),
      version: get().version + 1,
    });

    try {
      const body: Record<string, any> = {};
      if (updates.name !== undefined) body.name = updates.name;
      if (updates.color !== undefined) body.color = updates.color;
      if (updates.icon !== undefined) body.icon = updates.icon;
      if (updates.is_disabled !== undefined) body.is_disabled = updates.is_disabled;

      const updated = await apiFetch<UserCategory>(ENDPOINTS.updateCategory(id), {
        method: "PUT",
        body: JSON.stringify(body),
      });

      // Replace with server response
      set({
        items: get().items.map((c) =>
          c.id === id ? { ...updated, color: updated.color ?? undefined, icon: updated.icon ?? undefined } : c
        ),
      });
    } catch {
      // Revert optimistic update
      set({ items: prev, version: get().version + 1 });
    }
  },

  removeCategoryById: async (id) => {
    const prev = get().items;
    set({
      items: prev.filter((c) => c.id !== id),
      version: get().version + 1,
    });

    try {
      await apiFetch(ENDPOINTS.category(id), { method: "DELETE" });
    } catch {
      // Revert
      set({ items: prev, version: get().version + 1 });
    }
  },

  removeCategory: async (type, category) => {
    const target = get().items.find((c) => c.type === type && c.name === category);
    if (!target) return;

    // Optimistic remove
    const prev = get().items;
    set({
      items: prev.filter((c) => c.id !== target.id),
      version: get().version + 1,
    });

    try {
      await apiFetch(ENDPOINTS.category(target.id), { method: "DELETE" });
    } catch {
      // Revert
      set({ items: prev, version: get().version + 1 });
    }
  },
}));
